### ISSUE TITLE
Maven tests fail on windows

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera#183]
The maven build tests for n5 fail on windows.
These failures actually occurred when trying to build paintera from source on windows 10
and I have only copied the relevant part from the tests here.
Judging from the error message, I would assume there is some issue with `/` vs `\`
Also pinging @hanslovsky.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.janelia.saalfeldlab.util.n5.N5HelpersTest
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.2 s <<< FAILURE! - in org.janelia.saalfeldlab.util.n5.N5HelpersTest
[ERROR] testListAndSortScaleDatasets(org.janelia.saalfeldlab.util.n5.N5HelpersTest)  Time elapsed: 0.166 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<group[/]s0> but was:<group[\]s0>
        at org.janelia.saalfeldlab.util.n5.N5HelpersTest.testListAndSortScaleDatasets(N5HelpersTest.java:79)

[ERROR] testHighestResolutionDataset(org.janelia.saalfeldlab.util.n5.N5HelpersTest)  Time elapsed: 0.006 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<group[/]s0> but was:<group[\]s0>
        at org.janelia.saalfeldlab.util.n5.N5HelpersTest.testHighestResolutionDataset(N5HelpersTest.java:95)

[INFO] Running org.janelia.saalfeldlab.util.n5.N5TypesTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in org.janelia.saalfeldlab.util.n5.N5TypesTest
[INFO] Running org.janelia.saalfeldlab.util.SetsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.janelia.saalfeldlab.util.SetsTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   N5HelpersTest.testHighestResolutionDataset:95 expected:<group[/]s0> but was:<group[\]s0>
[ERROR]   N5HelpersTest.testListAndSortScaleDatasets:79 expected:<group[/]s0> but was:<group[\]s0>
[INFO]
[ERROR] Tests run: 41, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2019-01-21T13:20:52+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project paintera: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Software\paintera-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

C:\Software\paintera-master>mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\Software\apache-maven-3.6.0\bin\..
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_202\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by hanslovsky** [comment]
@axtimwalde 
> Java filesystem ops are supposed to work with "/" cross-platform. Do not use system specific stuff. Can this be closed?

Not sure what you mean by *system specific stuff*. `N5Helpers.getFinestLevel` uses `Paths.get` as is used in `N5FSWriter.createGroup`.

Anyway, this issue can be fixed by replacing
```java
Assert.assertEquals("group/s0", N5Helpers.getFinestLevel(writer, group));
```
with
```java
Assert.assertEquals(Paths.join("group", "s0"), N5Helpers.getFinestLevel(writer, group));
```
and any equivalent lines in `N5HelpersTest`.

**Comment by axtimwalde** [comment]
Perfect. I didn't look deeply into this.  Was just confused about the "/" vs "\" stuff.
