### ISSUE TITLE
0.14.1 breaks Lauritzen projects with synapse rendering

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#239]
Starting Paintera with a Lauritzen project with synapse rendering hangs on start-up with a thread deadlock before the UI shows up. This happens with 0.14.1 but not with 0.14.0, so it may have been introduced in #222. I do not have the time to look into it right now, so I recommend users working on Lauritzen projects with syanpse rendering stick with 0.14.0 for now (you will only miss out on global interpolation instead of per source interpolation). I might have a little bit of free time at the hackathon on Wednesday and hopefully, I can fix this.

**Comment by hanslovsky** [comment]
It may be unrelated and just happened to surface at the same time as the release (I was able to start without deadlock a few times). I will investigate more. For now, the (relevant portions of the) thread dump:
```
Found one Java-level deadlock:
=============================
"painter-thread":
  waiting to lock monitor 0x00007fb7d0309eb8 (object 0x0000000435488420, a bdv.fx.viewer.ViewerState),
  which is held by "JavaFX Application Thread"
"JavaFX Application Thread":
  waiting to lock monitor 0x00007fb7d0308498 (object 0x00000004354af1e8, a bdv.fx.viewer.render.RenderUnit),
  which is held by "painter-thread"

Java stack information for the threads listed above:
===================================================
"painter-thread":
        at bdv.fx.viewer.render.RenderUnit.paint(RenderUnit.java:238)
        - waiting to lock <0x0000000435488420> (a bdv.fx.viewer.ViewerState)
        - locked <0x00000004354af1e8> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.render.PainterThread.run(PainterThread.java:46)
"JavaFX Application Thread":
        at bdv.fx.viewer.render.RenderUnit.requestRepaint(RenderUnit.java:122)
        - waiting to lock <0x00000004354af1e8> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.ViewerPanelFX.requestRepaint(ViewerPanelFX.java:330)
        at bdv.fx.viewer.ViewerPanelFX.lambda$new$0(ViewerPanelFX.java:196)
        at bdv.fx.viewer.ViewerPanelFX$$Lambda$135/1687069163.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at bdv.fx.viewer.ViewerPanelFX.setAllSources(ViewerPanelFX.java:228)
        - locked <0x0000000435488420> (a bdv.fx.viewer.ViewerState)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.lambda$setAllSources$1(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews$$Lambda$865/1243007179.accept(Unknown Source)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.applyToAll(OrthogonalViews.java:171)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.setAllSources(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.lambda$new$2(PainteraBaseView.java:164)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView$$Lambda$156/66555712.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$0(FXCollections.java:929)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl$$Lambda$47/1761531904.onChanged(Unknown Source)
        at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSourcesAndConverters(SourceInfo.java:350)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$new$5(SourceInfo.java:97)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$88/238711863.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSources(SourceInfo.java:345)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$new$4(SourceInfo.java:86)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$87/411450648.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
        at java.util.AbstractList.add(AbstractList.java:108)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:179)
        - locked <0x00000004352b3af0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:168)
        - locked <0x00000004352b3af0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addGenericState(PainteraBaseView.java:267)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addState(PainteraBaseView.java:248)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$382/1630139119.accept(Unknown Source)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer$$Lambda$804/853709544.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer.populate(SourceInfoSerializer.java:103)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.lambda$fromSerializedProperties$8(Properties.java:214)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$381/1803116267.accept(Unknown Source)
        at pl.touk.throwing.ThrowingConsumer.lambda$uncheck$20(ThrowingConsumer.java:72)
        at pl.touk.throwing.ThrowingConsumer$$Lambda$380/1639747128.accept(Unknown Source)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:213)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:141)
        at org.janelia.saalfeldlab.paintera.Paintera.lambda$startImpl$5(Paintera.java:177)
        at org.janelia.saalfeldlab.paintera.Paintera$$Lambda$342/960003418.apply(Unknown Source)
        at pl.touk.throwing.ThrowingFunction.lambda$uncheck$8(ThrowingFunction.java:95)
        at pl.touk.throwing.ThrowingFunction$$Lambda$343/2130753444.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
        at org.janelia.saalfeldlab.paintera.Paintera.startImpl(Paintera.java:177)
        at org.janelia.saalfeldlab.paintera.Paintera.start(Paintera.java:80)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.LauncherImpl$$Lambda$58/80246425.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl$$Lambda$50/411631404.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl$$Lambda$53/1504179820.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.javafx.application.PlatformImpl$$Lambda$51/1688019098.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at com.sun.glass.ui.gtk.GtkApplication$$Lambda$41/1748225580.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**Comment by hanslovsky** [comment]
Looking at the stack information I am more convinced that the co-occurence with the global interpolation toggle is coincidental and a deeper race condition just surfaced.

**Comment by hanslovsky** [comment]
I am also getting this race condition at a smaller project:
```
Found one Java-level deadlock:
=============================
"painter-thread":
  waiting to lock monitor 0x00007f07ec2cc208 (object 0x00000002c1a29480, a bdv.fx.viewer.ViewerState),
  which is held by "JavaFX Application Thread"
"JavaFX Application Thread":
  waiting to lock monitor 0x00007f07ec2cad68 (object 0x00000002c1445e98, a bdv.fx.viewer.render.RenderUnit),
  which is held by "painter-thread"

Java stack information for the threads listed above:
===================================================
"painter-thread":
        at bdv.fx.viewer.render.RenderUnit.paint(RenderUnit.java:238)
        - waiting to lock <0x00000002c1a29480> (a bdv.fx.viewer.ViewerState)
        - locked <0x00000002c1445e98> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.render.PainterThread.run(PainterThread.java:46)
"JavaFX Application Thread":
        at bdv.fx.viewer.render.RenderUnit.requestRepaint(RenderUnit.java:122)
        - waiting to lock <0x00000002c1445e98> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.ViewerPanelFX.requestRepaint(ViewerPanelFX.java:332)
        at bdv.fx.viewer.ViewerPanelFX.lambda$new$0(ViewerPanelFX.java:196)
        at bdv.fx.viewer.ViewerPanelFX$$Lambda$135/543913576.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at bdv.fx.viewer.ViewerPanelFX.setAllSources(ViewerPanelFX.java:230)
        - locked <0x00000002c1a29480> (a bdv.fx.viewer.ViewerState)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.lambda$setAllSources$1(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews$$Lambda$798/712347284.accept(Unknown Source)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.applyToAll(OrthogonalViews.java:171)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.setAllSources(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.lambda$new$2(PainteraBaseView.java:162)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView$$Lambda$168/1767770418.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$0(FXCollections.java:929)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl$$Lambda$47/1556224432.onChanged(Unknown Source)
        at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSourcesAndConverters(SourceInfo.java:350)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$new$5(SourceInfo.java:97)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$88/410770048.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSources(SourceInfo.java:345)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$new$4(SourceInfo.java:86)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$87/1816766955.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
        at java.util.AbstractList.add(AbstractList.java:108)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:179)
        - locked <0x00000002c145e0e0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:168)
        - locked <0x00000002c145e0e0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addGenericState(PainteraBaseView.java:265)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addState(PainteraBaseView.java:246)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$407/1815158122.accept(Unknown Source)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer$$Lambda$739/997936073.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer.populate(SourceInfoSerializer.java:103)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.lambda$fromSerializedProperties$11(Properties.java:239)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$406/989771895.accept(Unknown Source)
        at pl.touk.throwing.ThrowingConsumer.lambda$uncheck$20(ThrowingConsumer.java:72)
        at pl.touk.throwing.ThrowingConsumer$$Lambda$405/120020439.accept(Unknown Source)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:238)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:152)
        at org.janelia.saalfeldlab.paintera.Paintera.lambda$startImpl$5(Paintera.java:187)
        at org.janelia.saalfeldlab.paintera.Paintera$$Lambda$363/720033158.apply(Unknown Source)
        at pl.touk.throwing.ThrowingFunction.lambda$uncheck$8(ThrowingFunction.java:95)
        at pl.touk.throwing.ThrowingFunction$$Lambda$364/501842674.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
        at org.janelia.saalfeldlab.paintera.Paintera.startImpl(Paintera.java:187)
        at org.janelia.saalfeldlab.paintera.Paintera.start(Paintera.java:81)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.LauncherImpl$$Lambda$58/1237496459.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl$$Lambda$50/1513712028.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl$$Lambda$53/1084326333.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.javafx.application.PlatformImpl$$Lambda$51/1456208737.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at com.sun.glass.ui.gtk.GtkApplication$$Lambda$41/2101440631.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.

project `attributes.xml`:
```xml
{
  "n5": "2.0.2",
  "paintera": {
    "sourceInfo": {
      "sources": [
        {
          "type": "org.janelia.saalfeldlab.paintera.state.RawSourceState",
          "state": {
            "composite": {},
            "converter": {
              "alpha": 1.0,
              "color": "#FFFFFF",
              "min": 0.0,
              "max": 255.0
            },
            "compositeType": "org.janelia.saalfeldlab.paintera.composition.CompositeCopy",
            "converterType": "net.imglib2.converter.ARGBColorConverter$InvertingImp1",
            "interpolation": "NEARESTNEIGHBOR",
            "isVisible": true,
            "sourceType": "org.janelia.saalfeldlab.paintera.data.n5.N5DataSource",
            "source": {
              "metaType": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
              "meta": {
                "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                "dataset": "/volumes/raw"
              },
              "transform": [
                4.0,
                0.0,
                0.0,
                0.0,
                0.0,
                4.0,
                0.0,
                0.0,
                0.0,
                0.0,
                40.0,
                0.0
              ]
            },
            "name": "raw",
            "dependsOn": [],
            "axisOrder": "XYZ"
          }
        },
        {
          "type": "org.janelia.saalfeldlab.paintera.state.LabelSourceState",
          "state": {
            "composite": {},
            "converter": {
              "converterType": "org.janelia.saalfeldlab.paintera.stream.HighlightingStreamConverterLabelMultisetType",
              "streamType": "org.janelia.saalfeldlab.paintera.stream.ModalGoldenAngleSaturatedHighlightingARGBStream",
              "seed": 1
            },
            "compositeType": "org.janelia.saalfeldlab.paintera.composition.ARGBCompositeAlphaYCbCr",
            "converterType": "org.janelia.saalfeldlab.paintera.stream.HighlightingStreamConverterLabelMultisetType",
            "interpolation": "NEARESTNEIGHBOR",
            "isVisible": true,
            "sourceType": "org.janelia.saalfeldlab.paintera.data.mask.MaskedSource",
            "source": {
              "source": {
                "metaType": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
                "meta": {
                  "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                  "dataset": "/volumes/labels/neuron_ids"
                },
                "transform": [
                  4.0,
                  0.0,
                  0.0,
                  3644.0,
                  0.0,
                  4.0,
                  0.0,
                  3644.0,
                  0.0,
                  0.0,
                  40.0,
                  1520.0
                ]
              },
              "sourceClass": "org.janelia.saalfeldlab.paintera.data.n5.N5DataSource",
              "persistCanvasClass": "org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5",
              "persistCanvas": {
                "class": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
                "data": {
                  "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                  "dataset": "/volumes/labels/neuron_ids"
                }
              }
            },
            "name": "neuron_ids",
            "dependsOn": [],
            "axisOrder": "XYZ",
            "selectedIds": {
              "lastSelection": -2,
              "activeIds": [
                -2
              ]
            },
            "assignment": {
              "type": "org.janelia.saalfeldlab.paintera.control.assignment.FragmentSegmentAssignmentOnlyLocal",
              "data": {
                "actions": [],
                "persister": {
                  "type": "org.janelia.saalfeldlab.util.n5.N5FragmentSegmentAssignmentPersister",
                  "data": {
                    "N5": {
                      "type": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
                      "data": {
                        "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                        "dataset": "/volumes/labels/neuron_ids/fragment-segment-assignment"
                      }
                    }
                  }
                },
                "initialLut": {
                  "type": "org.janelia.saalfeldlab.util.n5.N5FragmentSegmentAssignmentInitialLut",
                  "data": {
                    "N5": {
                      "type": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
                      "data": {
                        "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                        "dataset": "/volumes/labels/neuron_ids/fragment-segment-assignment"
                      }
                    }
                  }
                }
              }
            },
            "lockedSegments": [],
            "meshSettings": {
              "globalSettings": {
                "numScaleLevels": 7,
                "scaleLevel": 6,
                "simplificationIterations": 0,
                "smoothingLambda": 0.5,
                "smoothingIterations": 3,
                "opacity": 1.0,
                "inflate": 1.0,
                "isVisible": true,
                "drawMode": "FILL",
                "cullFace": "FRONT"
              },
              "meshSettings": []
            },
            "labelBlockMapping": {
              "type": "n5-filesystem",
              "root": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
              "scaleDatasetPattern": "volumes/labels/neuron_ids/label-to-block-mapping/s%d"
            },
            "idService": {
              "type": "org.janelia.saalfeldlab.paintera.id.N5IdService",
              "data": {
                "N5": {
                  "type": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
                  "data": {
                    "n5": "/data/hanslovskyp/cremi/sample_A_padded_20160501.n5",
                    "dataset": "/volumes/labels/neuron_ids"
                  }
                }
              }
            }
          }
        }
      ],
      "currentSourceIndex": 0,
      "numSources": 2
    },
    "globalTransform": [
      0.16443563297285874,
      0.0,
      0.0,
      -1200.3312703076144,
      0.0,
      0.1644356329728588,
      0.0,
      -1147.8819925930534,
      0.0,
      0.0,
      0.16443563297285865,
      -565.7147369081313
    ],
    "windowProperties": {
      "width": 800,
      "height": 800
    },
    "gridConstraints": {
      "previousFirstRowHeight": 50.0,
      "previousFirstColumnWidth": 50.0,
      "isFullScreen": false,
      "firstRowHeight": 50.0,
      "firstColumnWidth": 50.0
    },
    "crosshairConfig": {
      "onFocusColor": "#FF0088FF",
      "offFocusColor": "#FFFFFF80",
      "isVisible": true
    },
    "orthoSliceConfig": {
      "enabled": true,
      "showTopLeft": true,
      "showTopRight": true,
      "showBottomLeft": true
    },
    "navigationConfig": {
      "allowRotations": true,
      "buttonRotationSpeeds": {
        "slow": 0.5,
        "regular": 5.0,
        "fast": 45.0
      }
    },
    "viewer3DConfig": {
      "areMeshesEnabled": true
    },
    "screenScalesConfig": {
      "scales": [
        1.0,
        0.5,
        0.25
      ]
    },
    "scaleBarOverlayConfig": {
      "overlayFont": {
        "name": "System Regular",
        "size": 18.0
      },
      "foregroundColor": "#FFFFFFFF",
      "backgroundColor": "#00000088",
      "isShowing": false,
      "targetScaleBarLength": 200.0
    }
  }
}
```

**Comment by igorpisarev** [comment]
For some reason this started happening quite frequently to me in the last couple of days, so I'm having a look at it
