### ISSUE TITLE
Cannot call PainteraBaseView.addSingleScaleLabelSource

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#241]
Trying to run the [payntera blobs examples](https://github.com/saalfeldlab/payntera/blob/e717166ff16de823c16322d0f7f42f69424d67f1/example-blobs.py) with the latest release of Paintera but `PainteraBaseView.addSingleScaleLabelSource` throws a `NullPointerException`:

```
java.lang.NullPointerException
org.janelia.saalfeldlab.paintera.state.LabelSourceState.createDisplayStatus(LabelSourceState.java:667)
org.janelia.saalfeldlab.paintera.state.LabelSourceState.<init>(LabelSourceState.java:165)
org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:425)
org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:310)
org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:269)
org.janelia.saalfeldlab.paintera.PainteraBaseView.addSingleScaleLabelSource(PainteraBaseView.java:373)
org.janelia.saalfeldlab.paintera.PainteraBaseView.addSingleScaleLabelSource(PainteraBaseView.java:349)
```

**Comment by hanslovsky** [comment]
MWE:
```java
import com.sun.javafx.application.PlatformImpl;
import net.imglib2.RandomAccessibleInterval;
import net.imglib2.img.array.ArrayImgs;
import net.imglib2.type.numeric.integer.UnsignedLongType;
import org.janelia.saalfeldlab.paintera.PainteraBaseView;
import org.janelia.saalfeldlab.paintera.data.axisorder.AxisOrderNotSupported;

import java.io.IOException;

public class NPE {

    public static void main(String[] args) throws IOException, AxisOrderNotSupported {
        PlatformImpl.startup(() -> {});
        final RandomAccessibleInterval<UnsignedLongType> labels = ArrayImgs.unsignedLongs(10, 20, 30);
        final PainteraBaseView.DefaultPainteraBaseView viewer = PainteraBaseView.defaultView();
        viewer.baseView.addSingleScaleLabelSource(
                labels,
                new double[] {1.0, 1.0, 1.0},
                new double[] {0.0, 0.0, 0.0},
                1,
                "blub");
    }
}
```

```
Exception in thread "main" java.lang.NullPointerException
	at org.janelia.saalfeldlab.paintera.state.LabelSourceState.createDisplayStatus(LabelSourceState.java:667)
	at org.janelia.saalfeldlab.paintera.state.LabelSourceState.<init>(LabelSourceState.java:165)
	at org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:425)
	at org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:310)
	at org.janelia.saalfeldlab.paintera.state.LabelSourceState.simpleSourceFromSingleRAI(LabelSourceState.java:269)
	at org.janelia.saalfeldlab.paintera.PainteraBaseView.addSingleScaleLabelSource(PainteraBaseView.java:373)
	at org.janelia.saalfeldlab.paintera.PainteraBaseView.addSingleScaleLabelSource(PainteraBaseView.java:349)
	at NPE.main(NPE.java:19)
```
