### ISSUE TITLE
Create standalone app

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#253]
The installation process is hard for people who are not familiar with command line and conda. To make Paintera more accessible, we should try to create standalone packages that ideally ships Java as well.

[Self contained packaging](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html) through the `javapackager` might be a good way to do that. I tried so far, with mixed success. For all cases, add these lines to `pom.xml` inside the `<prpofiles></profiles>` tag:
```xml
<profile>
	<id>with-slf4j-simple</id>
	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>${slf4j-simple.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</profile>
```

### [`javafx-maven-plugin`](https://github.com/javafx-maven-plugin/javafx-maven-plugin)

Add these lines to `pom.xml`:
```xml
<build>
	<plugins>
		<plugin>
			<groupId>com.zenjava</groupId>
			<artifactId>javafx-maven-plugin</artifactId>
			<version>8.8.3</version>
			<configuration>
				<mainClass>${main-class}</mainClass>
			</configuration>
		</plugin>
	</plugins>
</build>
```
Then run
```
mvn -Pwith-slf4j-simple jfx:native
target/jfx/native/Paintera/Paintera
```
 - native executable works
 - version string is not available: `[JavaFX Application Thread] INFO org.janelia.saalfeldlab.paintera.PainteraCommandLineArgs - Paintera version: null`
 - weird delay when clicking "No Project" in initial dialog

Not sure if this package is still maintained (last commit in March of 2018) and is a package with [the same artifactId](https://github.com/openjfx/javafx-maven-plugin) but I do not know if and how they are related.

### Build uber jar and then use `javapackager`

Add these lines to `pom.xml` inside the `<profiles></profiles>` tag:
```xml
<profile>
	<id>uber</id>
	<build>
		<plugins>
			<!-- Maven Assembly Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					<!-- get all project dependencies -->
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<!-- MainClass in mainfest make a executable jar -->
					<archive>
						<manifest>
							<mainClass>${main-class}</mainClass>
						</manifest>
					</archive>

				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<!-- bind to the packaging phase -->
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</profile>
```
Then run
```
mvn -Pwith-slf4j-simple,uber clean package
java -jar target/paintera-0.16.1-SNAPSHOT-jar-with-dependencies.jar
```

 - version is overwritten to `2.77.0` (probably resolvable with shading)
 - no SciJava plugins are detected, i.e. cannot open dataset (serialization wouldn't work either)

If those issue can be resolved, then package it with
```
javapackager  \
    -deploy \
    -name Paintera \
    -native \
    -outdir out \
    -outfile paintera \
    -srcdir target \
    -srcfiles paintera-0.16.1-SNAPSHOT-jar-with-dependencies.jar  \
    -appclass org.janelia.saalfeldlab.paintera.Paintera
```
When packaged natively, there is also a weird delay also observed with `javafx-maven-plugin`.

### Build shaded jar and then use `javapackager`

Add these lines to `pom.xml` inside the `<profiles></profiles>` tag:
```xml
<profile>
	<id>shaded</id>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>META-INF/*.SF</exclude>
								<exclude>META-INF/*.DSA</exclude>
								<exclude>META-INF/*.RSA</exclude>
							</excludes>
						</filter>
					</filters>
					<artifactSet>
						<excludes>
							<exclude>*hadoop*</exclude>
							<exclude>*spark*</exclude>
							<exclude>*scala*</exclude>
						</excludes>
					</artifactSet>
					<shadedArtifactId>${project.artifactId}</shadedArtifactId>
					<shadedArtifactAttached>true</shadedArtifactAttached>
					<!-- Do not minimize for now to speed up packaging. -->
					<!-- <minimzeJar>true</minimzeJar> -->

					<relocations>
						<relocation>
							<pattern>org.apache.commons.compress</pattern>
							<shadedPattern>org.janelia.saalfeldlab.org.apache.commons.compress</shadedPattern>
						</relocation>
					</relocations>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>${main-class}</mainClass>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</profile>
```
Then run
```
mvn -Pwith-slf4j-simple,shaded clean package
java -jar target/paintera-0.16.1-SNAPSHOT-shaded.jar
```

 - version is correct
 - Crashes when clicking `No Proejct`:
 ```
 [WARNING] Class pool is empty: forgot to call Thread#setClassLoader?
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.<init>(PainteraBaseView.java:93)
        at org.janelia.saalfeldlab.paintera.Paintera.startImpl(Paintera.java:149)
        at org.janelia.saalfeldlab.paintera.Paintera.start(Paintera.java:81)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        ... 1 more
Caused by: pl.touk.throwing.exception.WrappedException: No compatible service: org.scijava.plugin.PluginService
        at pl.touk.throwing.ThrowingSupplier.lambda$uncheck$22(ThrowingSupplier.java:63)
        at org.janelia.saalfeldlab.paintera.cache.DiscoverableMemoryUsage.<clinit>(DiscoverableMemoryUsage.java:22)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: No compatible service: org.scijava.plugin.PluginService
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:244)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:195)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:171)
        at org.scijava.Context.<init>(Context.java:281)
        at org.scijava.Context.<init>(Context.java:237)
        at org.scijava.Context.<init>(Context.java:177)
        at org.scijava.Context.<init>(Context.java:163)
        at org.janelia.saalfeldlab.paintera.cache.DiscoverableMemoryUsage.discoverAll(DiscoverableMemoryUsage.java:38)
        at pl.touk.throwing.ThrowingSupplier.lambda$uncheck$22(ThrowingSupplier.java:61)
        ... 13 more
Exception running application org.janelia.saalfeldlab.paintera.Paintera
```

### General Issues:
 - It is unclear if it is possible to specify JVM arguments, e.g. `-Xmx60g` from the command line when using the native app.

**Comment by hanslovsky** [comment]
Relevant for #251

**Comment by hanslovsky** [comment]
Possibly related:
https://bugs.openjdk.java.net/browse/JDK-8138944

**Comment by hanslovsky** [comment]
Also related (and look who created that post :smile:):
https://stackoverflow.com/questions/30809330/how-can-dynamic-jvm-command-line-flags-be-passed-to-a-self-contained-javafx-appl

**Comment by hanslovsky** [comment]
Also have a look at `jpackage`:
https://www.infoq.com/news/2019/03/jep-343-jpackage/
https://jdk.java.net/jpackage/

Probably(?) not compatible with Java8.

**Comment by constantinpape** [comment]
I don't know if this has been discussed elsewhere, but would it be possible to ship with Fiji? I.e. adding it via a paintera update site.
This would be the easiest way to deploy it to users.

**Comment by hanslovsky** [comment]
Unfortunately, that is not possible because Fiji uses swing/awt and Paintera uses the JavaFX UI framework. Interop is not great between those

**Comment by constantinpape** [comment]
> Unfortunately, that is not possible because Fiji uses swing/awt and Paintera uses the JavaFX UI framework. Interop is not great between those

Thanks for the clarification.
In that case, having a standalone app would indeed be a very good solution.
Once you have a first version, I am happy to test.

**Comment by hanslovsky** [comment]
I think the easiest way for ward is to create tar/zip files with (or without) the required Java Runtime and all Jars and shell (Linux/macOS) and batch (Windows) scripts that execute that, with installers for macOS/Windows and deb (or other packages) for Linux. I will not be at Janelia much longer, so I will not be able to address this but this may be a good community contribution because it does not require any (deep) knowledge about Java programming.

Also, cc @igorpisarev and @axtimwalde

**Comment by cmhulbert** [comment]
The most recent Paintera release now has some platform specific standalone installers for MacOS, Windows, and Ubuntu. It's not currently a replacement for the conda release process, but it's useful for installing a version that tracks against the master branch. It uses the [jtoolprovider-plugin](https://github.com/wiverson/jtoolprovider-plugin) for maven, which facilitates using `jpackage` to generate the standalone JRE. 

It's triggered on pushes to master, through github actions, so should always track with the most recent master commit. 

The README has [some more information about it](https://github.com/saalfeldlab/paintera#development-releases), including some known limitations at the moment.

Releases are here: https://github.com/saalfeldlab/paintera/releases

**Comment by tinevez** [comment]
I tested it this morning on a Mac M2. And it works! Great job!.

**Comment by axtimwalde** [comment]
This is surprising because we do not build releases for M1/2...

**Comment by cmhulbert** [comment]
To be clear, it can be done, I have tested locally on an M1 and it works well. But the github automatic releases are not built on M1/M2 Macs. It's something I hope to set up soon, as we refine this release process

**Comment by tinevez** [comment]
Well, to me it looks like you are very good at it for something you don't do:

<img width="1027" alt="Screenshot 2023-06-08 at 07 14 19" src="https://github.com/saalfeldlab/paintera/assets/3583203/2e5a6f2d-b1d1-4411-bbaf-669fc8c04d0d">

**Comment by cmhulbert** [comment]
Currently, the Github Actions based release is the formal release, so I will close this as done. There are still some questions about publishing the releases to native store, and how to automate updates, but I think those are best tracked in dedicated issues.
