### ISSUE TITLE
Deadlock at startup

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#288]
I ran into this deadlock when starting the application with an existing project. Although this happened on another branch, I don't think that I modified the affected code, so the same thing may happen in the current master branch (my branch is up-to-date with the current master). It's probably a rare occurrence since it's the first time I'm running into this.

Basically it looks like `RenderUnit` and `ViewerState` are locked by different threads in inverse order:

```
"painter-thread":
        at bdv.fx.viewer.render.RenderUnit.paint(RenderUnit.java:238)
        - waiting to lock <0x00007fdf98240978> (a bdv.fx.viewer.ViewerState)
        - locked <0x00007fdf982187c8> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.render.PainterThread.run(PainterThread.java:46)

"JavaFX Application Thread":
        at bdv.fx.viewer.render.RenderUnit.requestRepaint(RenderUnit.java:122)
        - waiting to lock <0x00007fdf982187c8> (a bdv.fx.viewer.render.RenderUnit)
        at bdv.fx.viewer.ViewerPanelFX.requestRepaint(ViewerPanelFX.java:332)
        at bdv.fx.viewer.ViewerPanelFX.lambda$0(ViewerPanelFX.java:196)
        at bdv.fx.viewer.ViewerPanelFX$$Lambda$144/428613767.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at bdv.fx.viewer.ViewerPanelFX.setAllSources(ViewerPanelFX.java:230)
        - locked <0x00007fdf98240978> (a bdv.fx.viewer.ViewerState)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.lambda$2(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews$$Lambda$817/863982207.accept(Unknown Source)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.applyToAll(OrthogonalViews.java:171)
        at org.janelia.saalfeldlab.fx.ortho.OrthogonalViews.setAllSources(OrthogonalViews.java:204)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.lambda$5(PainteraBaseView.java:165)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView$$Lambda$175/440916172.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$3(FXCollections.java:929)
        at javafx.collections.FXCollections$UnmodifiableObservableListImpl$$Lambda$47/1705483771.onChanged(Unknown Source)
        at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSourcesAndConverters(SourceInfo.java:350)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$7(SourceInfo.java:97)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$94/1317649179.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.updateVisibleSources(SourceInfo.java:345)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.lambda$6(SourceInfo.java:86)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo$$Lambda$93/542507138.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
        at java.util.AbstractList.add(AbstractList.java:108)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:179)
        - locked <0x00007fdf982576d0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.state.SourceInfo.addState(SourceInfo.java:168)
        - locked <0x00007fdf982576d0> (a org.janelia.saalfeldlab.paintera.state.SourceInfo)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addGenericState(PainteraBaseView.java:268)
        at org.janelia.saalfeldlab.paintera.PainteraBaseView.addState(PainteraBaseView.java:249)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$432/353988006.accept(Unknown Source)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer$$Lambda$747/181675904.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer.populate(SourceInfoSerializer.java:103)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.lambda$18(Properties.java:250)
        at org.janelia.saalfeldlab.paintera.serialization.Properties$$Lambda$431/409466883.accept(Unknown Source)
        at com.pivovarit.function.ThrowingConsumer.lambda$uncheck$3(ThrowingConsumer.java:87)
        at com.pivovarit.function.ThrowingConsumer$$Lambda$430/1625007357.accept(Unknown Source)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:249)
        at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:158)
        at org.janelia.saalfeldlab.paintera.Paintera.lambda$4(Paintera.java:187)
        at org.janelia.saalfeldlab.paintera.Paintera$$Lambda$386/1279252327.apply(Unknown Source)
        at com.pivovarit.function.ThrowingFunction.lambda$uncheck$4(ThrowingFunction.java:84)
        at com.pivovarit.function.ThrowingFunction$$Lambda$387/728755670.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
        at org.janelia.saalfeldlab.paintera.Paintera.startImpl(Paintera.java:187)
        at org.janelia.saalfeldlab.paintera.Paintera.start(Paintera.java:81)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$419(LauncherImpl.java:863)
        at com.sun.javafx.application.LauncherImpl$$Lambda$58/1047320648.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$399(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl$$Lambda$50/693632176.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$397(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl$$Lambda$53/1933291332.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$398(PlatformImpl.java:294)
        at com.sun.javafx.application.PlatformImpl$$Lambda$52/1364335809.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
        at com.sun.glass.ui.gtk.GtkApplication$$Lambda$41/2027961269.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**Comment by hanslovsky** [comment]
This is probably a duplicate of #239 

I haven't had the time to look into it, yet.

**Comment by igorpisarev** [comment]
Yes, the stack traces indeed are identical. I'm closing this as duplicate then
