### ISSUE TITLE
"Not a label multiset" error when persisting canvas

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#297]
The following exception is thrown when trying to persist the canvas because `isLabelMultiset` attribute is missing in downsampled label datasets:
```
java.io.IOException: /volumes/segmentation/multicut/data/s1 is not a label multiset dataset.
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:120)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:100)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:83)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:66)
    at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.downsampleAndWriteBlocksLabelMultisetType(CommitCanvasN5.java:660)
    at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.persistCanvas(CommitCanvasN5.java:272)
    at org.janelia.saalfeldlab.paintera.data.mask.MaskedSource.lambda$persistCanvas$13(MaskedSource.java:606)
    at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-63" java.lang.RuntimeException: Error while trying to persist.
    at org.janelia.saalfeldlab.paintera.data.mask.MaskedSource.lambda$persistCanvas$13(MaskedSource.java:621)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.janelia.saalfeldlab.paintera.data.mask.persist.UnableToPersistCanvas: Unable to commit canvas.
    at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.persistCanvas(CommitCanvasN5.java:304)
    at org.janelia.saalfeldlab.paintera.data.mask.MaskedSource.lambda$persistCanvas$13(MaskedSource.java:606)
    ... 1 more
Caused by: java.io.IOException: /volumes/segmentation/multicut/data/s1 is not a label multiset dataset.
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:120)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:100)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:83)
    at org.janelia.saalfeldlab.n5.imglib2.N5LabelMultisets.openLabelMultiset(N5LabelMultisets.java:66)
    at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.downsampleAndWriteBlocksLabelMultisetType(CommitCanvasN5.java:660)
    at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.persistCanvas(CommitCanvasN5.java:272)
    ... 2 more
```

This started happening after https://github.com/saalfeldlab/paintera/pull/281, where I switched to `N5LabelMutlisets` for reading label mutliset data, which requires `isLabelMutliset` attribute as it doesn't differentiate between full-res and downsampled datsets.

**Comment by hanslovsky** [comment]
Thank you @igorpisarev
