### ISSUE TITLE
Unable to commit canvas

### ISSUE THREAD

**Issue by cpatrickc** [saalfeldlab/paintera#374]
Unable to commit canvas: lateinit property container has not been initialized

```
[Thread-78] INFO org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5 - Committing canvas: 1 blocks
[Thread-78] INFO org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5 - Finished commiting canvas
Exception in thread "Thread-78" kotlin.UninitializedPropertyAccessException: lateinit property container has not been initialized
	at org.janelia.saalfeldlab.labels.blocks.n5.LabelBlockLookupFromN5Relative.getBlockKey(LabelBlockLookupFromN5Relative.kt:147)
	at org.janelia.saalfeldlab.labels.blocks.n5.LabelBlockLookupFromN5Relative.getBlockKey(LabelBlockLookupFromN5Relative.kt:143)
	at org.janelia.saalfeldlab.labels.blocks.n5.LabelBlockLookupFromN5Relative.read(LabelBlockLookupFromN5Relative.kt:86)
	at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.updateLabelBlockLookup(CommitCanvasN5.java:164)
	at org.janelia.saalfeldlab.paintera.data.mask.MaskedSource.lambda$persistCanvas$13(MaskedSource.java:639)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hanslovsky** [comment]
Fixed in #377
