### ISSUE TITLE
Paintera Process not exiting when closing application

### ISSUE THREAD

**Issue by cmhulbert** [saalfeldlab/paintera#479]
reported by @axtimwalde 
Associated stacktrace when forcing the process to quit via `Ctrl-C`
```
Traceback (most recent call last):
  File "/home/saalfelds/anaconda3/envs/paintera/bin/paintera", line 11, in <module>
    sys.exit(launch_paintera())
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/site-packages/paintera/__init__.py", line 59, in launch_paintera
    return jgo.util.main_from_endpoint(
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/site-packages/jgo/util.py", line 71, in main_from_endpoint
    main(argv=argv)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/site-packages/jgo/jgo.py", line 290, in _jgo_main
    completed_process = run(parser, argv=argv, stdout=stdout, stderr=stderr)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/site-packages/jgo/jgo.py", line 588, in run
    return launch_java(workspace, jvm_args, main_class, *program_args, additional_jars=args.additional_jars, stdout=stdout, stderr=stderr, check=False)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/site-packages/jgo/jgo.py", line 197, in launch_java
    return subprocess.run((java, '-cp', cp) + jvm_args + (main_class,) + app_args, stdout=stdout, stderr=stderr, **subprocess_run_kwargs)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/subprocess.py", line 1141, in communicate
    self.wait()
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/saalfelds/anaconda3/envs/paintera/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by cmhulbert** [comment]
@axtimwalde do you have steps that duplicate this?
I've tried just opening an existing project, do some painting/shape interpolation operations and then closing, but the process quits properly when exiting.

**Comment by axtimwalde** [comment]
Nothing special. Open, close. Did you test the release version?

**Comment by axtimwalde** [comment]
Also, I am working on a project on a network drive, may be speed matters.

**Comment by cmhulbert** [comment]
> Nothing special. Open, close. Did you test the release version?

Yes, I was testing against the current release. I have seen similar issue while debugging for example, but can't duplicate with the release. I'll keep trying. I can test over the network also

**Comment by axtimwalde** [comment]
It's the MIDI controller!  Needs to be closed at exit or will prevent JVM from closing.  You should use it more :).

**Comment by cmhulbert** [comment]
Thanks for investigating. I should be able to get a quick fix for this then :+1:

**Comment by cmhulbert** [comment]
Seems this is a known bug (https://bugs.openjdk.org/browse/JDK-8232862). This results in the Midi device thread never returning cooperatively when closing the midi device. When Paintera quits, it calls `Platform.exit` which is specific to closing as JavaFx application. However, this differs from `System.exit` in that it does't force non-`daemon` threads to return. The result is that the Midi thread is still running. Until the bug is fixed at least, there should be no harm in explicitly calling `System.exit` after`Platform.exit`

**Comment by axtimwalde** [comment]
Update: We just tested n5-utils and n5-viewer in Fiji that both use a copy of the same MIDI controller and both applications terminate successfully.
