### ISSUE TITLE
Problem installing Paintera on Windows 10

### ISSUE THREAD

**Issue by ofrag** [saalfeldlab/paintera#515]
Hi,

I’m trying to follow the instructions for installing paintera on Windows 10 from [image,sc forum](https://forum.image.sc/t/paintera-installation-in-windows-10/46409/2), I run the suggested commands in the created environment: 

```
conda install -c pkgs/main openjdk
conda install -c conda-forge maven
conda install -c conda-forge paintera
paintera --help

```
after the installation, I get the following error message.
any advise would be appreciated

```
INFO 2023-10-22 17:04:42,150: First time start-up may be slow. Downloaded dependencies will be cached for shorter start-up times in subsequent executions.
Traceback (most recent call last):
  File "d:\Users\ofrag\.conda\envs\paintera\Scripts\paintera-script.py", line 10, in <module>
    sys.exit(launch_paintera())
             ^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\paintera\__init__.py", line 59, in launch_paintera
    return jgo.util.main_from_endpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\jgo\util.py", line 101, in main_from_endpoint
    main(argv=argv)
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\jgo\jgo.py", line 404, in _jgo_main
    completed_process = run(parser, argv=argv, stdout=stdout, stderr=stderr)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\jgo\jgo.py", line 781, in run
    primary_endpoint, workspace = resolve_dependencies(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\jgo\jgo.py", line 641, in resolve_dependencies
    mvn_out = run_and_combine_outputs(mvn, *mvn_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\site-packages\jgo\jgo.py", line 270, in run_and_combine_outputs
    return subprocess.check_output(command_string, stderr=subprocess.STDOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "d:\Users\ofrag\.conda\envs\paintera\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```
Ofra

**Comment by cmhulbert** [comment]
Thanks for reporting! 
Unfortunately I won't be able to look at this issue for a bit, but in the meantime, if you would like to download the pre-release Windows installer (it should be the same version as the most recent conda package) you can find it here!

https://github.com/saalfeldlab/paintera/releases/tag/windows-latest

**Comment by ofrag** [comment]
Thanks,

Having the windows installer is great. I installed and start using it. 
Thanks
Ofra

**Comment by cmhulbert** [comment]
Closing this, as the formal release process has moved to the platform installers on [Github Releases](https://github.com/saalfeldlab/paintera/releases)
