### ISSUE TITLE
canvas saving fails with block-size mismatch

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#99]
```
[Thread-599] ERROR org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5 - Canvas grid CellGrid( dims = (5950, 6428, 500), cellDims = (256, 256, 26) ) and highest resolution dataset grid CellGrid( dims = (30000, 30000, 1875), cellDims = (128, 128, 26) ) incompatible!
Exception in thread "Thread-599" java.lang.RuntimeException: Canvas grid CellGrid( dims = (5950, 6428, 500), cellDims = (256, 256, 26) ) and highest resolution dataset grid CellGrid( dims = (30000, 30000, 1875), cellDims = (128, 128, 26) ) incompatible!
	at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.accept(CommitCanvasN5.java:88)
	at org.janelia.saalfeldlab.paintera.data.n5.CommitCanvasN5.accept(CommitCanvasN5.java:1)
	at org.janelia.saalfeldlab.paintera.data.mask.MaskedSource.lambda$25(MaskedSource.java:455)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hanslovsky** [comment]
This is caused by inconsistent `attributes.json`. Change
```
"persistCanvas": {
  "class": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
  "data": {
    "n5": "/nrs/saalfeld/sample_E/sample_E.n5/volumes",
    "dataset": "/multicut-mipmap-label-lists-128,128,26"
  }
}
```
to
```
"persistCanvas": {
  "class": "org.janelia.saalfeldlab.paintera.data.n5.N5FSMeta",
  "data": {
    "n5": "/nrs/saalfeld/lauritzen/02/workspace.n5",
    "dataset": "/raw/segmentations/multires/mc_glia_global2_multires"
  }
}
```
